import fs from 'node:fs/promises';
import path from 'node:path';
import { escapeHtml as esc } from './runtime.mjs';
export async function creativeHtml(fields,kind,sourceDir) {
 const c=fields.creative[kind],legacy=kind==='legacy',annual=kind==='annual';
 const hero=(await fs.readFile(path.join(sourceDir,'hero.png'))).toString('base64');
 const price=legacy?fields.legacyPrice:annual?fields.savingsHeadline:fields.starterMonthly;
 const detail=annual?fields.annualSavings:c.body;
 const secondary=annual?'Starter is $288 a year.':null;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(c.title.replace('\n',' '))}</title><style>
*{box-sizing:border-box}html,body{margin:0}body{background:#f5f1e7;color:#163c30;font-family:Arial,Helvetica,sans-serif}.creative{width:1080px;height:1080px;position:relative;overflow:hidden;background:${legacy?'#163c30':'#f5f1e7'};color:${legacy?'#f5f1e7':'#163c30'}}.photo{position:absolute;right:0;top:0;width:430px;height:1080px;object-fit:cover;object-position:58% center}.copy{position:relative;display:flex;flex-direction:column;padding:56px;width:650px;height:1080px}.brand{font-size:42px;font-weight:700;letter-spacing:-2px}.eyebrow{font-size:17px;font-weight:700;letter-spacing:2px;margin-top:68px;margin-bottom:28px;line-height:1.5}h1{font-family:Georgia,'Times New Roman',serif;font-weight:400;letter-spacing:-3px;font-size:80px;line-height:1.08;margin:0;white-space:pre-line}.body{font-size:23px;line-height:1.5;margin:28px 0 0}.price{font-family:Georgia,'Times New Roman',serif;font-size:${annual?'152px':'45px'};font-weight:400;line-height:1.16;margin:${annual?'30px':'44px'} 0 0;letter-spacing:-1px}.detail{font-size:23px;line-height:1.45;margin:18px 0 0}.secondary{font-size:22px;margin:16px 0 0}.qualifier{font-size:17px;line-height:1.5;margin:24px 0 0;max-width:510px}.bottom{margin-top:auto}.cta{font-size:21px;font-weight:700;border-top:1px solid ${legacy?'#7b9685':'#a4b09f'};padding-top:25px;margin:0 0 25px}.disclosure{font-size:15px;margin:0;color:${legacy?'#c7d7ce':'#546b60'}}
</style></head><body><main class="creative" aria-label="Fictional MOGS campaign"><img class="photo" src="data:image/png;base64,${hero}" alt="A sunlit workspace with a forest-green chair and an open notebook"><div class="copy"><div class="brand">mogs.</div><p class="eyebrow">${esc(c.eyebrow)}</p><h1>${esc(c.title)}</h1>${annual?'':`<p class="body">${esc(c.body)}</p>`}<p class="price" data-source-id="${annual?'savings-headline':'monthly-price'}">${esc(price)}</p>${annual?`<p class="detail" data-source-id="annual-savings">${esc(detail)}</p><p class="secondary" data-source-id="annual-price">${esc(secondary)}</p>`:''}<p class="qualifier" data-source-id="eligibility">${esc(c.qualifier)}</p><div class="bottom"><p class="cta">${esc(c.cta)}</p><p class="disclosure">Fictional MOGS campaign · October 2026</p></div></div></main></body></html>\n`;
}
